//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GIRServiceReference
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
    public partial class FaultDetail : object
    {
        
        private string CodeField;
        
        private string MessageField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Code
        {
            get
            {
                return this.CodeField;
            }
            set
            {
                this.CodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message
        {
            get
            {
                return this.MessageField;
            }
            set
            {
                this.MessageField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSIdentityCreate", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
    public partial class WSIdentityCreate : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string CuIdField;
        
        private System.Nullable<System.DateTime> DepartureDateField;
        
        private string DescriptionField;
        
        private System.Nullable<bool> DirectorySyncField;
        
        private string DomainField;
        
        private string EmailField;
        
        private string EmployeeCategoryField;
        
        private System.Nullable<System.DateTime> EntryDateField;
        
        private string FirstNameField;
        
        private bool GassiField;
        
        private string GroupSubsidiaryField;
        
        private string LastNameField;
        
        private string LocalIdField;
        
        private string ManagerField;
        
        private string ManagerRHField;
        
        private string MiddleNameField;
        
        private string NotificationMailField;
        
        private string PartnerField;
        
        private string PreferredFirstNameField;
        
        private string PreferredLastNameField;
        
        private string PrefixField;
        
        private bool ReportingGlobalField;
        
        private string SubCategoryField;
        
        private string TitleField;
        
        private System.Nullable<bool> VipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuId
        {
            get
            {
                return this.CuIdField;
            }
            set
            {
                this.CuIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> DepartureDate
        {
            get
            {
                return this.DepartureDateField;
            }
            set
            {
                this.DepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> DirectorySync
        {
            get
            {
                return this.DirectorySyncField;
            }
            set
            {
                this.DirectorySyncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string EmployeeCategory
        {
            get
            {
                return this.EmployeeCategoryField;
            }
            set
            {
                this.EmployeeCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public System.Nullable<System.DateTime> EntryDate
        {
            get
            {
                return this.EntryDateField;
            }
            set
            {
                this.EntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Gassi
        {
            get
            {
                return this.GassiField;
            }
            set
            {
                this.GassiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupSubsidiary
        {
            get
            {
                return this.GroupSubsidiaryField;
            }
            set
            {
                this.GroupSubsidiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalId
        {
            get
            {
                return this.LocalIdField;
            }
            set
            {
                this.LocalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string Manager
        {
            get
            {
                return this.ManagerField;
            }
            set
            {
                this.ManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerRH
        {
            get
            {
                return this.ManagerRHField;
            }
            set
            {
                this.ManagerRHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationMail
        {
            get
            {
                return this.NotificationMailField;
            }
            set
            {
                this.NotificationMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partner
        {
            get
            {
                return this.PartnerField;
            }
            set
            {
                this.PartnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredFirstName
        {
            get
            {
                return this.PreferredFirstNameField;
            }
            set
            {
                this.PreferredFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredLastName
        {
            get
            {
                return this.PreferredLastNameField;
            }
            set
            {
                this.PreferredLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool ReportingGlobal
        {
            get
            {
                return this.ReportingGlobalField;
            }
            set
            {
                this.ReportingGlobalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategory
        {
            get
            {
                return this.SubCategoryField;
            }
            set
            {
                this.SubCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Vip
        {
            get
            {
                return this.VipField;
            }
            set
            {
                this.VipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="IdentityDumpResponse", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
    public partial class IdentityDumpResponse : object
    {
        
        private GIRServiceReference.WSIdentity identityField;
        
        private bool successField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public GIRServiceReference.WSIdentity identity
        {
            get
            {
                return this.identityField;
            }
            set
            {
                this.identityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool success
        {
            get
            {
                return this.successField;
            }
            set
            {
                this.successField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="WSIdentity", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
    public partial class WSIdentity : object
    {
        
        private System.Nullable<System.DateTime> BirthDateField;
        
        private string CuIdField;
        
        private System.DateTime DepartureDateField;
        
        private string DescriptionField;
        
        private bool DirectorySyncField;
        
        private string DomainField;
        
        private string EmailField;
        
        private string EmployeeCategoryField;
        
        private System.DateTime EntryDateField;
        
        private System.DateTime FirstEntryDateField;
        
        private string FirstNameField;
        
        private bool GassiField;
        
        private string GroupSubsidiaryField;
        
        private System.DateTime LastDepartureDateField;
        
        private string LastNameField;
        
        private string LocalIdField;
        
        private string ManagerField;
        
        private string ManagerRHField;
        
        private string MiddleNameField;
        
        private string NotificationMailField;
        
        private string PartnerField;
        
        private string PreferredFirstNameField;
        
        private string PreferredLastNameField;
        
        private string PrefixField;
        
        private bool ReportingGlobalField;
        
        private bool StatusField;
        
        private string SubCategoryField;
        
        private string TitleField;
        
        private System.Nullable<bool> VipField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.DateTime> BirthDate
        {
            get
            {
                return this.BirthDateField;
            }
            set
            {
                this.BirthDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CuId
        {
            get
            {
                return this.CuIdField;
            }
            set
            {
                this.CuIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DepartureDate
        {
            get
            {
                return this.DepartureDateField;
            }
            set
            {
                this.DepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description
        {
            get
            {
                return this.DescriptionField;
            }
            set
            {
                this.DescriptionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool DirectorySync
        {
            get
            {
                return this.DirectorySyncField;
            }
            set
            {
                this.DirectorySyncField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Domain
        {
            get
            {
                return this.DomainField;
            }
            set
            {
                this.DomainField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                this.EmailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmployeeCategory
        {
            get
            {
                return this.EmployeeCategoryField;
            }
            set
            {
                this.EmployeeCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime EntryDate
        {
            get
            {
                return this.EntryDateField;
            }
            set
            {
                this.EntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FirstEntryDate
        {
            get
            {
                return this.FirstEntryDateField;
            }
            set
            {
                this.FirstEntryDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FirstName
        {
            get
            {
                return this.FirstNameField;
            }
            set
            {
                this.FirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Gassi
        {
            get
            {
                return this.GassiField;
            }
            set
            {
                this.GassiField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GroupSubsidiary
        {
            get
            {
                return this.GroupSubsidiaryField;
            }
            set
            {
                this.GroupSubsidiaryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastDepartureDate
        {
            get
            {
                return this.LastDepartureDateField;
            }
            set
            {
                this.LastDepartureDateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LastName
        {
            get
            {
                return this.LastNameField;
            }
            set
            {
                this.LastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string LocalId
        {
            get
            {
                return this.LocalIdField;
            }
            set
            {
                this.LocalIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Manager
        {
            get
            {
                return this.ManagerField;
            }
            set
            {
                this.ManagerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ManagerRH
        {
            get
            {
                return this.ManagerRHField;
            }
            set
            {
                this.ManagerRHField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string MiddleName
        {
            get
            {
                return this.MiddleNameField;
            }
            set
            {
                this.MiddleNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NotificationMail
        {
            get
            {
                return this.NotificationMailField;
            }
            set
            {
                this.NotificationMailField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Partner
        {
            get
            {
                return this.PartnerField;
            }
            set
            {
                this.PartnerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredFirstName
        {
            get
            {
                return this.PreferredFirstNameField;
            }
            set
            {
                this.PreferredFirstNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PreferredLastName
        {
            get
            {
                return this.PreferredLastNameField;
            }
            set
            {
                this.PreferredLastNameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prefix
        {
            get
            {
                return this.PrefixField;
            }
            set
            {
                this.PrefixField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ReportingGlobal
        {
            get
            {
                return this.ReportingGlobalField;
            }
            set
            {
                this.ReportingGlobalField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Status
        {
            get
            {
                return this.StatusField;
            }
            set
            {
                this.StatusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SubCategory
        {
            get
            {
                return this.SubCategoryField;
            }
            set
            {
                this.SubCategoryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Title
        {
            get
            {
                return this.TitleField;
            }
            set
            {
                this.TitleField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<bool> Vip
        {
            get
            {
                return this.VipField;
            }
            set
            {
                this.VipField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UpdatePrefixInput", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
    public partial class UpdatePrefixInput : object
    {
        
        private string CuIdField;
        
        private string PrefixValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public string CuId
        {
            get
            {
                return this.CuIdField;
            }
            set
            {
                this.CuIdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrefixValue
        {
            get
            {
                return this.PrefixValueField;
            }
            set
            {
                this.PrefixValueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Item", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
    public partial class Item : object
    {
        
        private string IdField;
        
        private string ValueField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Id
        {
            get
            {
                return this.IdField;
            }
            set
            {
                this.IdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Value
        {
            get
            {
                return this.ValueField;
            }
            set
            {
                this.ValueField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", ConfigurationName="GIRServiceReference.GIR_IOSWW")]
    public interface GIR_IOSWW
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetMinimalDate", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetMinimalDateR" +
            "esponse")]
        System.Threading.Tasks.Task<string> GetMinimalDateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetAllCategoryV" +
            "alues", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetAllCategoryV" +
            "aluesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetAllCategoryV" +
            "aluesFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<string[]> GetAllCategoryValuesAsync(byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/CreateIdentity", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/CreateIdentityR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/CreateIdentityF" +
            "aultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.IdentityDumpResponse> CreateIdentityAsync(GIRServiceReference.WSIdentityCreate ParamIdentity, System.Nullable<bool> ForceHomonymy, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/IsIdentity", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/IsIdentityRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/IsIdentityFault" +
            "DetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<bool> IsIdentityAsync(string CuId, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetIdentity", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetIdentityResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetIdentityFaul" +
            "tDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.WSIdentity> GetIdentityAsync(string CuId, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/Search", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/SearchResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/SearchFaultDeta" +
            "ilFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.WSIdentity[]> SearchAsync(string LastName, string FirstName, System.Nullable<System.DateTime> EntryDate, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdateIdentityF" +
            "ull", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdateIdentityF" +
            "ullResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdateIdentityF" +
            "ullFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.IdentityDumpResponse> UpdateIdentityFullAsync(GIRServiceReference.WSIdentityCreate ParamIdentity, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdateIdentityD" +
            "elta", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdateIdentityD" +
            "eltaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdateIdentityD" +
            "eltaFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.IdentityDumpResponse> UpdateIdentityDeltaAsync(
                    string cuId, 
                    string newTitle, 
                    string newLastName, 
                    string newLastNamePreferred, 
                    string newFirstName, 
                    string newFirstNamePreferred, 
                    string newMiddleName, 
                    string newEmployeeCategory, 
                    string newEntryDate, 
                    string newDepartureDate, 
                    string newManager, 
                    string newManagerRH, 
                    string newDescription, 
                    string newBirthDate, 
                    string newDomain, 
                    string newNotificationMail, 
                    string newLocalId, 
                    string newDirectorySync, 
                    string newGassi, 
                    string newReportingGlobal, 
                    byte[] certData, 
                    string newGroupSubsidiary, 
                    string newPartner);
        
        // CODEGEN: Generating message contract since the operation has multiple return values.
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/ReplaceManager", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/ReplaceManagerR" +
            "esponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/ReplaceManagerF" +
            "aultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.ReplaceManagerResponse> ReplaceManagerAsync(GIRServiceReference.ReplaceManagerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdatePrefix", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdatePrefixRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/UpdatePrefixFau" +
            "ltDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<string> UpdatePrefixAsync(GIRServiceReference.UpdatePrefixInput UpdatePrefixValue, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetStatus", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetStatusRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetStatusFaultD" +
            "etailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<bool> GetStatusAsync(string CuId, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/SetStatus", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/SetStatusRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/SetStatusFaultD" +
            "etailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<bool> SetStatusAsync(string CuId, bool Status, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetDefaultBirth" +
            "date", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetDefaultBirth" +
            "dateResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetDefaultBirth" +
            "dateFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<string> GetDefaultBirthdateAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/AddDomain", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/AddDomainRespon" +
            "se")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/AddDomainFaultD" +
            "etailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<bool> AddDomainAsync(string CuId, string Domain, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/RemoveDomain", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/RemoveDomainRes" +
            "ponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/RemoveDomainFau" +
            "ltDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<bool> RemoveDomainAsync(string CuId, string Domain, byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetCategories", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetCategoriesRe" +
            "sponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetCategoriesFa" +
            "ultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetCategoriesAsync(byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetDomains", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetDomainsRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetDomainsFault" +
            "DetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetDomainsAsync(byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetGroupSubsidi" +
            "aries", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetGroupSubsidi" +
            "ariesResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetGroupSubsidi" +
            "ariesFaultDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetGroupSubsidiariesAsync(byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetPartners", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetPartnersResp" +
            "onse")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/GetPartnersFaul" +
            "tDetailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetPartnersAsync(byte[] certData);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/Esearch", ReplyAction="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/EsearchResponse" +
            "")]
        [System.ServiceModel.FaultContractAttribute(typeof(GIRServiceReference.FaultDetail), Action="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW/GIR_IOSWW/EsearchFaultDet" +
            "ailFault", Name="FaultDetail", Namespace="http://schemas.datacontract.org/2004/07/FT.IAM.GIR.WCF_IOSWW")]
        System.Threading.Tasks.Task<GIRServiceReference.WSIdentity[]> EsearchAsync(string Title, string CuId, string Domain, string EmployeeCategory, string LastName, string FirstName, string Manager, System.Nullable<System.DateTime> EntryDate, System.Nullable<System.DateTime> DepartureDate, string LocalId, string Email, string Prefix, System.Nullable<bool> Status, byte[] certData);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceManager", WrapperNamespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", IsWrapped=true)]
    public partial class ReplaceManagerRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", Order=0)]
        public string CuIdMngrToReplace;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", Order=1)]
        public string CuIdNewMngr;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", Order=2)]
        public byte[] certData;
        
        public ReplaceManagerRequest()
        {
        }
        
        public ReplaceManagerRequest(string CuIdMngrToReplace, string CuIdNewMngr, byte[] certData)
        {
            this.CuIdMngrToReplace = CuIdMngrToReplace;
            this.CuIdNewMngr = CuIdNewMngr;
            this.certData = certData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ReplaceManagerResponse", WrapperNamespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", IsWrapped=true)]
    public partial class ReplaceManagerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", Order=0)]
        public bool ReplaceManagerResult;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", Order=1)]
        public string[] SuccessfulIdentitiesIds;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://basicat.francetelecom.fr/IAM/GIR/G2R1/G2R1_IOSWW", Order=2)]
        public string[] FailedIdentitiesIds;
        
        public ReplaceManagerResponse()
        {
        }
        
        public ReplaceManagerResponse(bool ReplaceManagerResult, string[] SuccessfulIdentitiesIds, string[] FailedIdentitiesIds)
        {
            this.ReplaceManagerResult = ReplaceManagerResult;
            this.SuccessfulIdentitiesIds = SuccessfulIdentitiesIds;
            this.FailedIdentitiesIds = FailedIdentitiesIds;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface GIR_IOSWWChannel : GIRServiceReference.GIR_IOSWW, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class GIR_IOSWWClient : System.ServiceModel.ClientBase<GIRServiceReference.GIR_IOSWW>, GIRServiceReference.GIR_IOSWW
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public GIR_IOSWWClient() : 
                base(GIR_IOSWWClient.GetDefaultBinding(), GIR_IOSWWClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_GIR_IOSWW.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GIR_IOSWWClient(EndpointConfiguration endpointConfiguration) : 
                base(GIR_IOSWWClient.GetBindingForEndpoint(endpointConfiguration), GIR_IOSWWClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GIR_IOSWWClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(GIR_IOSWWClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GIR_IOSWWClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(GIR_IOSWWClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public GIR_IOSWWClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<string> GetMinimalDateAsync()
        {
            return base.Channel.GetMinimalDateAsync();
        }
        
        public System.Threading.Tasks.Task<string[]> GetAllCategoryValuesAsync(byte[] certData)
        {
            return base.Channel.GetAllCategoryValuesAsync(certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.IdentityDumpResponse> CreateIdentityAsync(GIRServiceReference.WSIdentityCreate ParamIdentity, System.Nullable<bool> ForceHomonymy, byte[] certData)
        {
            return base.Channel.CreateIdentityAsync(ParamIdentity, ForceHomonymy, certData);
        }
        
        public System.Threading.Tasks.Task<bool> IsIdentityAsync(string CuId, byte[] certData)
        {
            return base.Channel.IsIdentityAsync(CuId, certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.WSIdentity> GetIdentityAsync(string CuId, byte[] certData)
        {
            return base.Channel.GetIdentityAsync(CuId, certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.WSIdentity[]> SearchAsync(string LastName, string FirstName, System.Nullable<System.DateTime> EntryDate, byte[] certData)
        {
            return base.Channel.SearchAsync(LastName, FirstName, EntryDate, certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.IdentityDumpResponse> UpdateIdentityFullAsync(GIRServiceReference.WSIdentityCreate ParamIdentity, byte[] certData)
        {
            return base.Channel.UpdateIdentityFullAsync(ParamIdentity, certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.IdentityDumpResponse> UpdateIdentityDeltaAsync(
                    string cuId, 
                    string newTitle, 
                    string newLastName, 
                    string newLastNamePreferred, 
                    string newFirstName, 
                    string newFirstNamePreferred, 
                    string newMiddleName, 
                    string newEmployeeCategory, 
                    string newEntryDate, 
                    string newDepartureDate, 
                    string newManager, 
                    string newManagerRH, 
                    string newDescription, 
                    string newBirthDate, 
                    string newDomain, 
                    string newNotificationMail, 
                    string newLocalId, 
                    string newDirectorySync, 
                    string newGassi, 
                    string newReportingGlobal, 
                    byte[] certData, 
                    string newGroupSubsidiary, 
                    string newPartner)
        {
            return base.Channel.UpdateIdentityDeltaAsync(cuId, newTitle, newLastName, newLastNamePreferred, newFirstName, newFirstNamePreferred, newMiddleName, newEmployeeCategory, newEntryDate, newDepartureDate, newManager, newManagerRH, newDescription, newBirthDate, newDomain, newNotificationMail, newLocalId, newDirectorySync, newGassi, newReportingGlobal, certData, newGroupSubsidiary, newPartner);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.ReplaceManagerResponse> ReplaceManagerAsync(GIRServiceReference.ReplaceManagerRequest request)
        {
            return base.Channel.ReplaceManagerAsync(request);
        }
        
        public System.Threading.Tasks.Task<string> UpdatePrefixAsync(GIRServiceReference.UpdatePrefixInput UpdatePrefixValue, byte[] certData)
        {
            return base.Channel.UpdatePrefixAsync(UpdatePrefixValue, certData);
        }
        
        public System.Threading.Tasks.Task<bool> GetStatusAsync(string CuId, byte[] certData)
        {
            return base.Channel.GetStatusAsync(CuId, certData);
        }
        
        public System.Threading.Tasks.Task<bool> SetStatusAsync(string CuId, bool Status, byte[] certData)
        {
            return base.Channel.SetStatusAsync(CuId, Status, certData);
        }
        
        public System.Threading.Tasks.Task<string> GetDefaultBirthdateAsync()
        {
            return base.Channel.GetDefaultBirthdateAsync();
        }
        
        public System.Threading.Tasks.Task<bool> AddDomainAsync(string CuId, string Domain, byte[] certData)
        {
            return base.Channel.AddDomainAsync(CuId, Domain, certData);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveDomainAsync(string CuId, string Domain, byte[] certData)
        {
            return base.Channel.RemoveDomainAsync(CuId, Domain, certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetCategoriesAsync(byte[] certData)
        {
            return base.Channel.GetCategoriesAsync(certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetDomainsAsync(byte[] certData)
        {
            return base.Channel.GetDomainsAsync(certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetGroupSubsidiariesAsync(byte[] certData)
        {
            return base.Channel.GetGroupSubsidiariesAsync(certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.Item[]> GetPartnersAsync(byte[] certData)
        {
            return base.Channel.GetPartnersAsync(certData);
        }
        
        public System.Threading.Tasks.Task<GIRServiceReference.WSIdentity[]> EsearchAsync(string Title, string CuId, string Domain, string EmployeeCategory, string LastName, string FirstName, string Manager, System.Nullable<System.DateTime> EntryDate, System.Nullable<System.DateTime> DepartureDate, string LocalId, string Email, string Prefix, System.Nullable<bool> Status, byte[] certData)
        {
            return base.Channel.EsearchAsync(Title, CuId, Domain, EmployeeCategory, LastName, FirstName, Manager, EntryDate, DepartureDate, LocalId, Email, Prefix, Status, certData);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_GIR_IOSWW))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_GIR_IOSWW))
            {
                return new System.ServiceModel.EndpointAddress("http://girintg2web2.adint.imr.francetelecom.fr:8091/GIR_IOSWW.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return GIR_IOSWWClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_GIR_IOSWW);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return GIR_IOSWWClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_GIR_IOSWW);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_GIR_IOSWW,
        }
    }
}
