// <auto-generated />
namespace IDW.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class intial_migration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(intial_migration));
        
        string IMigrationMetadata.Id
        {
            get { return "201610301126380_intial_migration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
