// <auto-generated />
namespace ContosoUniversity.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class EnterpriseApp : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EnterpriseApp));
        
        string IMigrationMetadata.Id
        {
            get { return "201702140505422_EnterpriseApp"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
