// <auto-generated />
namespace ContosoUniversity.Data.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class changedmodel4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changedmodel4));
        
        string IMigrationMetadata.Id
        {
            get { return "201702140647021_changedmodel4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
