// <auto-generated />
namespace MovieListApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddDataAnnotationMig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddDataAnnotationMig));
        
        string IMigrationMetadata.Id
        {
            get { return "201701270531505_AddDataAnnotationMig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
