// <auto-generated />
namespace MovieListApp.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class AddRatingRig : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddRatingRig));
        
        string IMigrationMetadata.Id
        {
            get { return "201701270431543_AddRatingRig"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
