//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     //
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TigerServiceReference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.dto.ws.box.orange.com/")]
    public partial class FaultDetail
    {
        
        private string codeField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BWSManagerReplacement))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.dto.ws.box.orange.com/")]
    public partial class BWSSynchronousResponse
    {
        
        private long requestIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long requestId
        {
            get
            {
                return this.requestIdField;
            }
            set
            {
                this.requestIdField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://dto.id.service.ws.box.orange.com/")]
    public partial class BWSManagerReplacement : BWSSynchronousResponse
    {
        
        private string impactedIdentityCUIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string impactedIdentityCUID
        {
            get
            {
                return this.impactedIdentityCUIDField;
            }
            set
            {
                this.impactedIdentityCUIDField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://id.service.ws.box.orange.com/", ConfigurationName="TigerServiceReference.IdentityService")]
    public interface IdentityService
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TigerServiceReference.FaultDetail), Action="", Name="faultDetail", Namespace="http://common.dto.ws.box.orange.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TigerServiceReference.removeAdditionalAddressesResponse> removeAdditionalAddressesAsync(TigerServiceReference.removeAdditionalAddresses request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TigerServiceReference.FaultDetail), Action="", Name="faultDetail", Namespace="http://common.dto.ws.box.orange.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TigerServiceReference.generateMailAddressResponse> generateMailAddressAsync(TigerServiceReference.generateMailAddress request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TigerServiceReference.FaultDetail), Action="", Name="faultDetail", Namespace="http://common.dto.ws.box.orange.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TigerServiceReference.createResponse> createAsync(TigerServiceReference.create request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TigerServiceReference.FaultDetail), Action="", Name="faultDetail", Namespace="http://common.dto.ws.box.orange.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TigerServiceReference.addAdditionalAddressesResponse> addAdditionalAddressesAsync(TigerServiceReference.addAdditionalAddresses request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TigerServiceReference.FaultDetail), Action="", Name="faultDetail", Namespace="http://common.dto.ws.box.orange.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TigerServiceReference.replaceManagerResponse> replaceManagerAsync(TigerServiceReference.replaceManager request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(TigerServiceReference.FaultDetail), Action="", Name="faultDetail", Namespace="http://common.dto.ws.box.orange.com/")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<TigerServiceReference.modifyResponse> modifyAsync(TigerServiceReference.modify request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAdditionalAddresses", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class removeAdditionalAddresses
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] additionalAddresses;
        
        public removeAdditionalAddresses()
        {
        }
        
        public removeAdditionalAddresses(string cuid, string[] additionalAddresses)
        {
            this.cuid = cuid;
            this.additionalAddresses = additionalAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeAdditionalAddressesResponse", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class removeAdditionalAddressesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSSynchronousResponse @return;
        
        public removeAdditionalAddressesResponse()
        {
        }
        
        public removeAdditionalAddressesResponse(TigerServiceReference.BWSSynchronousResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateMailAddress", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class generateMailAddress
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuid;
        
        public generateMailAddress()
        {
        }
        
        public generateMailAddress(string cuid)
        {
            this.cuid = cuid;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateMailAddressResponse", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class generateMailAddressResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSSynchronousResponse @return;
        
        public generateMailAddressResponse()
        {
        }
        
        public generateMailAddressResponse(TigerServiceReference.BWSSynchronousResponse @return)
        {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.dto.ws.box.orange.com/")]
    public partial class BWSIdentity : BWSLightIdentity
    {
        
        private BWSTitle titleField;
        
        private deletableString preferredFirstNameField;
        
        private deletableString middleNameField;
        
        private deletableString preferredLastNameField;
        
        private deletableDateTime birthDateField;
        
        private deletableString secondaryEmailAddressField;
        
        private deletableString localIdField;
        
        private deletableString employeeNumberField;
        
        private deletableString descriptionField;
        
        private deletableString partnerCodeField;
        
        private deletableString subsidiaryCodeField;
        
        private deletableString mobilePhoneNumberField;
        
        private deletableString phoneNumberField;
        
        private deletableString hrStatusField;
        
        private deletableString jobFunctionField;
        
        private deletableString entityField;
        
        private deletableString hrManagerField;
        
        private deletableString notificationMailField;
        
        private bool reportingGlobalEnabledField;
        
        private bool reportingGlobalEnabledFieldSpecified;
        
        private deletableString sipAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public BWSTitle title
        {
            get
            {
                return this.titleField;
            }
            set
            {
                this.titleField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public deletableString preferredFirstName
        {
            get
            {
                return this.preferredFirstNameField;
            }
            set
            {
                this.preferredFirstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public deletableString middleName
        {
            get
            {
                return this.middleNameField;
            }
            set
            {
                this.middleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public deletableString preferredLastName
        {
            get
            {
                return this.preferredLastNameField;
            }
            set
            {
                this.preferredLastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public deletableDateTime birthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public deletableString secondaryEmailAddress
        {
            get
            {
                return this.secondaryEmailAddressField;
            }
            set
            {
                this.secondaryEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public deletableString localId
        {
            get
            {
                return this.localIdField;
            }
            set
            {
                this.localIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public deletableString employeeNumber
        {
            get
            {
                return this.employeeNumberField;
            }
            set
            {
                this.employeeNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public deletableString description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public deletableString partnerCode
        {
            get
            {
                return this.partnerCodeField;
            }
            set
            {
                this.partnerCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public deletableString subsidiaryCode
        {
            get
            {
                return this.subsidiaryCodeField;
            }
            set
            {
                this.subsidiaryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public deletableString mobilePhoneNumber
        {
            get
            {
                return this.mobilePhoneNumberField;
            }
            set
            {
                this.mobilePhoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public deletableString phoneNumber
        {
            get
            {
                return this.phoneNumberField;
            }
            set
            {
                this.phoneNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public deletableString hrStatus
        {
            get
            {
                return this.hrStatusField;
            }
            set
            {
                this.hrStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public deletableString jobFunction
        {
            get
            {
                return this.jobFunctionField;
            }
            set
            {
                this.jobFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public deletableString entity
        {
            get
            {
                return this.entityField;
            }
            set
            {
                this.entityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public deletableString hrManager
        {
            get
            {
                return this.hrManagerField;
            }
            set
            {
                this.hrManagerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public deletableString notificationMail
        {
            get
            {
                return this.notificationMailField;
            }
            set
            {
                this.notificationMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=18)]
        public bool reportingGlobalEnabled
        {
            get
            {
                return this.reportingGlobalEnabledField;
            }
            set
            {
                this.reportingGlobalEnabledField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool reportingGlobalEnabledSpecified
        {
            get
            {
                return this.reportingGlobalEnabledFieldSpecified;
            }
            set
            {
                this.reportingGlobalEnabledFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=19)]
        public deletableString sipAddress
        {
            get
            {
                return this.sipAddressField;
            }
            set
            {
                this.sipAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.dto.ws.box.orange.com/")]
    public partial class BWSTitle
    {
        
        private bool deletionField;
        
        private bool deletionFieldSpecified;
        
        private BWSTitleValues valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deletion
        {
            get
            {
                return this.deletionField;
            }
            set
            {
                this.deletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletionSpecified
        {
            get
            {
                return this.deletionFieldSpecified;
            }
            set
            {
                this.deletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public BWSTitleValues Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.dto.ws.box.orange.com/")]
    public enum BWSTitleValues
    {
        
        /// <remarks/>
        UNKNOWN,
        
        /// <remarks/>
        MR,
        
        /// <remarks/>
        MRS,
        
        /// <remarks/>
        MISS,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://custom.type.ws.box.orange.com/")]
    public partial class deletableString
    {
        
        private bool deletionField;
        
        private bool deletionFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deletion
        {
            get
            {
                return this.deletionField;
            }
            set
            {
                this.deletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletionSpecified
        {
            get
            {
                return this.deletionFieldSpecified;
            }
            set
            {
                this.deletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://custom.type.ws.box.orange.com/")]
    public partial class deletableDateTime
    {
        
        private bool deletionField;
        
        private bool deletionFieldSpecified;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deletion
        {
            get
            {
                return this.deletionField;
            }
            set
            {
                this.deletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletionSpecified
        {
            get
            {
                return this.deletionFieldSpecified;
            }
            set
            {
                this.deletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(BWSIdentity))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://common.dto.ws.box.orange.com/")]
    public partial class BWSLightIdentity
    {
        
        private deletableString firstNameField;
        
        private deletableString lastNameField;
        
        private deletableDateTime startDateField;
        
        private deletableDateTime endDateField;
        
        private deletableString organizationField;
        
        private deletableString girDomainField;
        
        private deletableString managerCUIDField;
        
        private deletableString displayNameField;
        
        private deletableString custom1Field;
        
        private deletableString custom2Field;
        
        private deletableString custom3Field;
        
        private deletableString custom4Field;
        
        private deletableString custom5Field;
        
        private deletableInt profileField;
        
        private deletableString employeeTypeField;
        
        private deletableString mainEmailAddressField;
        
        private deletableString physicalAddressField;
        
        private bool hiddenField;
        
        private bool hiddenFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public deletableString firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public deletableString lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public deletableDateTime startDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public deletableDateTime endDate
        {
            get
            {
                return this.endDateField;
            }
            set
            {
                this.endDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public deletableString organization
        {
            get
            {
                return this.organizationField;
            }
            set
            {
                this.organizationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public deletableString girDomain
        {
            get
            {
                return this.girDomainField;
            }
            set
            {
                this.girDomainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public deletableString managerCUID
        {
            get
            {
                return this.managerCUIDField;
            }
            set
            {
                this.managerCUIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public deletableString displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public deletableString custom1
        {
            get
            {
                return this.custom1Field;
            }
            set
            {
                this.custom1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public deletableString custom2
        {
            get
            {
                return this.custom2Field;
            }
            set
            {
                this.custom2Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public deletableString custom3
        {
            get
            {
                return this.custom3Field;
            }
            set
            {
                this.custom3Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public deletableString custom4
        {
            get
            {
                return this.custom4Field;
            }
            set
            {
                this.custom4Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public deletableString custom5
        {
            get
            {
                return this.custom5Field;
            }
            set
            {
                this.custom5Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public deletableInt profile
        {
            get
            {
                return this.profileField;
            }
            set
            {
                this.profileField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=14)]
        public deletableString employeeType
        {
            get
            {
                return this.employeeTypeField;
            }
            set
            {
                this.employeeTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=15)]
        public deletableString mainEmailAddress
        {
            get
            {
                return this.mainEmailAddressField;
            }
            set
            {
                this.mainEmailAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=16)]
        public deletableString physicalAddress
        {
            get
            {
                return this.physicalAddressField;
            }
            set
            {
                this.physicalAddressField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=17)]
        public bool hidden
        {
            get
            {
                return this.hiddenField;
            }
            set
            {
                this.hiddenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hiddenSpecified
        {
            get
            {
                return this.hiddenFieldSpecified;
            }
            set
            {
                this.hiddenFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://custom.type.ws.box.orange.com/")]
    public partial class deletableInt
    {
        
        private bool deletionField;
        
        private bool deletionFieldSpecified;
        
        private int valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute()]
        public bool deletion
        {
            get
            {
                return this.deletionField;
            }
            set
            {
                this.deletionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool deletionSpecified
        {
            get
            {
                return this.deletionFieldSpecified;
            }
            set
            {
                this.deletionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute()]
        public int Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="create", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class create
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSIdentity identity;
        
        public create()
        {
        }
        
        public create(TigerServiceReference.BWSIdentity identity)
        {
            this.identity = identity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="createResponse", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class createResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSSynchronousResponse @return;
        
        public createResponse()
        {
        }
        
        public createResponse(TigerServiceReference.BWSSynchronousResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdditionalAddresses", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class addAdditionalAddresses
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=1)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute("address", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public string[] additionalAddresses;
        
        public addAdditionalAddresses()
        {
        }
        
        public addAdditionalAddresses(string cuid, string[] additionalAddresses)
        {
            this.cuid = cuid;
            this.additionalAddresses = additionalAddresses;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="addAdditionalAddressesResponse", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class addAdditionalAddressesResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSSynchronousResponse @return;
        
        public addAdditionalAddressesResponse()
        {
        }
        
        public addAdditionalAddressesResponse(TigerServiceReference.BWSSynchronousResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="replaceManager", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class replaceManager
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string oldManagerCUID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string newManagerCUID;
        
        public replaceManager()
        {
        }
        
        public replaceManager(string oldManagerCUID, string newManagerCUID)
        {
            this.oldManagerCUID = oldManagerCUID;
            this.newManagerCUID = newManagerCUID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="replaceManagerResponse", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class replaceManagerResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public TigerServiceReference.BWSManagerReplacement[] @return;
        
        public replaceManagerResponse()
        {
        }
        
        public replaceManagerResponse(TigerServiceReference.BWSManagerReplacement[] @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modify", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class modify
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string cuid;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSIdentity identity;
        
        public modify()
        {
        }
        
        public modify(string cuid, TigerServiceReference.BWSIdentity identity)
        {
            this.cuid = cuid;
            this.identity = identity;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modifyResponse", WrapperNamespace="http://dto.id.service.ws.box.orange.com/", IsWrapped=true)]
    public partial class modifyResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://dto.id.service.ws.box.orange.com/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public TigerServiceReference.BWSSynchronousResponse @return;
        
        public modifyResponse()
        {
        }
        
        public modifyResponse(TigerServiceReference.BWSSynchronousResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public interface IdentityServiceChannel : TigerServiceReference.IdentityService, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("dotnet-svcutil", "0.4.0.0")]
    public partial class IdentityServiceClient : System.ServiceModel.ClientBase<TigerServiceReference.IdentityService>, TigerServiceReference.IdentityService
    {
        
    /// <summary>
    /// Implement this partial method to configure the service endpoint.
    /// </summary>
    /// <param name="serviceEndpoint">The endpoint to configure</param>
    /// <param name="clientCredentials">The client credentials</param>
    static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public IdentityServiceClient() : 
                base(IdentityServiceClient.GetDefaultBinding(), IdentityServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.IdentityService.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(IdentityServiceClient.GetBindingForEndpoint(endpointConfiguration), IdentityServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(IdentityServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(IdentityServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public IdentityServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TigerServiceReference.removeAdditionalAddressesResponse> TigerServiceReference.IdentityService.removeAdditionalAddressesAsync(TigerServiceReference.removeAdditionalAddresses request)
        {
            return base.Channel.removeAdditionalAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TigerServiceReference.removeAdditionalAddressesResponse> removeAdditionalAddressesAsync(string cuid, string[] additionalAddresses)
        {
            TigerServiceReference.removeAdditionalAddresses inValue = new TigerServiceReference.removeAdditionalAddresses();
            inValue.cuid = cuid;
            inValue.additionalAddresses = additionalAddresses;
            return ((TigerServiceReference.IdentityService)(this)).removeAdditionalAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TigerServiceReference.generateMailAddressResponse> TigerServiceReference.IdentityService.generateMailAddressAsync(TigerServiceReference.generateMailAddress request)
        {
            return base.Channel.generateMailAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<TigerServiceReference.generateMailAddressResponse> generateMailAddressAsync(string cuid)
        {
            TigerServiceReference.generateMailAddress inValue = new TigerServiceReference.generateMailAddress();
            inValue.cuid = cuid;
            return ((TigerServiceReference.IdentityService)(this)).generateMailAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TigerServiceReference.createResponse> TigerServiceReference.IdentityService.createAsync(TigerServiceReference.create request)
        {
            return base.Channel.createAsync(request);
        }
        
        public System.Threading.Tasks.Task<TigerServiceReference.createResponse> createAsync(TigerServiceReference.BWSIdentity identity)
        {
            TigerServiceReference.create inValue = new TigerServiceReference.create();
            inValue.identity = identity;
            return ((TigerServiceReference.IdentityService)(this)).createAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TigerServiceReference.addAdditionalAddressesResponse> TigerServiceReference.IdentityService.addAdditionalAddressesAsync(TigerServiceReference.addAdditionalAddresses request)
        {
            return base.Channel.addAdditionalAddressesAsync(request);
        }
        
        public System.Threading.Tasks.Task<TigerServiceReference.addAdditionalAddressesResponse> addAdditionalAddressesAsync(string cuid, string[] additionalAddresses)
        {
            TigerServiceReference.addAdditionalAddresses inValue = new TigerServiceReference.addAdditionalAddresses();
            inValue.cuid = cuid;
            inValue.additionalAddresses = additionalAddresses;
            return ((TigerServiceReference.IdentityService)(this)).addAdditionalAddressesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TigerServiceReference.replaceManagerResponse> TigerServiceReference.IdentityService.replaceManagerAsync(TigerServiceReference.replaceManager request)
        {
            return base.Channel.replaceManagerAsync(request);
        }
        
        public System.Threading.Tasks.Task<TigerServiceReference.replaceManagerResponse> replaceManagerAsync(string oldManagerCUID, string newManagerCUID)
        {
            TigerServiceReference.replaceManager inValue = new TigerServiceReference.replaceManager();
            inValue.oldManagerCUID = oldManagerCUID;
            inValue.newManagerCUID = newManagerCUID;
            return ((TigerServiceReference.IdentityService)(this)).replaceManagerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<TigerServiceReference.modifyResponse> TigerServiceReference.IdentityService.modifyAsync(TigerServiceReference.modify request)
        {
            return base.Channel.modifyAsync(request);
        }
        
        public System.Threading.Tasks.Task<TigerServiceReference.modifyResponse> modifyAsync(string cuid, TigerServiceReference.BWSIdentity identity)
        {
            TigerServiceReference.modify inValue = new TigerServiceReference.modify();
            inValue.cuid = cuid;
            inValue.identity = identity;
            return ((TigerServiceReference.IdentityService)(this)).modifyAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IdentityService))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.IdentityService))
            {
                return new System.ServiceModel.EndpointAddress("http://10.195.216.122:9004/TGRWS-ws/IdentityService");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return IdentityServiceClient.GetBindingForEndpoint(EndpointConfiguration.IdentityService);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return IdentityServiceClient.GetEndpointAddress(EndpointConfiguration.IdentityService);
        }
        
        public enum EndpointConfiguration
        {
            
            IdentityService,
        }
    }
}
