//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class queryzoneEntities : DbContext
    {
        public queryzoneEntities()
            : base("name=queryzoneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tbl_entity_comex> tbl_entity_comex { get; set; }
        public DbSet<tbl_entity_countries> tbl_entity_countries { get; set; }
        public DbSet<tbl_gir_category> tbl_gir_category { get; set; }
        public DbSet<tbl_gir_domain> tbl_gir_domain { get; set; }
        public DbSet<tbl_gir_identity> tbl_gir_identity { get; set; }
        public DbSet<tbl_gir_identity_his> tbl_gir_identity_his { get; set; }
        public DbSet<tbl_gir_log> tbl_gir_log { get; set; }
        public DbSet<tbl_gir_partner> tbl_gir_partner { get; set; }
        public DbSet<tbl_gir_purge> tbl_gir_purge { get; set; }
        public DbSet<tbl_gir_subsidiary> tbl_gir_subsidiary { get; set; }
        public DbSet<tbl_manager> tbl_manager { get; set; }
        public DbSet<tbl_od_entity> tbl_od_entity { get; set; }
        public DbSet<tbl_od_identity> tbl_od_identity { get; set; }
        public DbSet<tbl_od_identity_his> tbl_od_identity_his { get; set; }
        public DbSet<tbl_od_location> tbl_od_location { get; set; }
        public DbSet<tbl_pz_acclaim> tbl_pz_acclaim { get; set; }
        public DbSet<tbl_pz_activity> tbl_pz_activity { get; set; }
        public DbSet<tbl_pz_announce> tbl_pz_announce { get; set; }
        public DbSet<tbl_pz_answer> tbl_pz_answer { get; set; }
        public DbSet<tbl_pz_blog> tbl_pz_blog { get; set; }
        public DbSet<tbl_pz_blogpost> tbl_pz_blogpost { get; set; }
        public DbSet<tbl_pz_comment> tbl_pz_comment { get; set; }
        public DbSet<tbl_pz_community> tbl_pz_community { get; set; }
        public DbSet<tbl_pz_content> tbl_pz_content { get; set; }
        public DbSet<tbl_pz_document> tbl_pz_document { get; set; }
        public DbSet<tbl_pz_groupmember> tbl_pz_groupmember { get; set; }
        public DbSet<tbl_pz_message> tbl_pz_message { get; set; }
        public DbSet<tbl_pz_poll> tbl_pz_poll { get; set; }
        public DbSet<tbl_pz_profile> tbl_pz_profile { get; set; }
        public DbSet<tbl_pz_profile_his> tbl_pz_profile_his { get; set; }
        public DbSet<tbl_pz_project> tbl_pz_project { get; set; }
        public DbSet<tbl_pz_question> tbl_pz_question { get; set; }
        public DbSet<tbl_pz_socialgroup> tbl_pz_socialgroup { get; set; }
        public DbSet<tbl_pz_statuslevelpoint> tbl_pz_statuslevelpoint { get; set; }
        public DbSet<tbl_pz_userrelation> tbl_pz_userrelation { get; set; }
        public DbSet<tbl_od_role> tbl_od_role { get; set; }
    }
}
