//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pz_answer
    {
        public int ThreadID { get; set; }
        public int MessageID { get; set; }
        public Nullable<long> ContainerTypeCode { get; set; }
        public string ContainerType { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<bool> HelpfulAnswer { get; set; }
        public Nullable<bool> CorrectAnswer { get; set; }
    }
}
