//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pz_document
    {
        public int InternalDocID { get; set; }
        public Nullable<int> UserID { get; set; }
        public string DocumentID { get; set; }
        public Nullable<long> ContainerTypeCode { get; set; }
        public string ContainerType { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public string Type { get; set; }
        public Nullable<int> EditPolicy { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<bool> Recommended { get; set; }
        public Nullable<int> MeanRating { get; set; }
        public Nullable<int> ReadCount { get; set; }
        public string CommentStatus { get; set; }
        public Nullable<int> WorkflowID { get; set; }
        public Nullable<int> VersionID { get; set; }
    }
}
