//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_od_identity
    {
        public string CUID { get; set; }
        public Nullable<sbyte> Title { get; set; }
        public string Last_Name { get; set; }
        public string First_Name { get; set; }
        public string Type_OD { get; set; }
        public string Mobile { get; set; }
        public string Phone_Number { get; set; }
        public string Fax { get; set; }
        public string Email { get; set; }
        public string Secretary_CUID { get; set; }
        public string Postal_Address { get; set; }
        public string Location_Code { get; set; }
        public string Entity { get; set; }
        public string Manager_CUID { get; set; }
        public string Category_Code { get; set; }
        public string Mission { get; set; }
        public string Function { get; set; }
        public string Activity1 { get; set; }
        public string Activity2 { get; set; }
        public string Skill { get; set; }
        public string Secondary_Entity { get; set; }
        public string Secondary_Manager_CUID { get; set; }
        public string Secondary_Secretary_CUID { get; set; }
        public string Local_ID { get; set; }
        public string Preferred_Language { get; set; }
        public string Country_GIR { get; set; }
        public string Country { get; set; }
        public Nullable<sbyte> Status { get; set; }
        public string Rank { get; set; }
        public string Room_Number { get; set; }
        public string Visiting_Card { get; set; }
        public string Visiting_Card_FR { get; set; }
        public string Visiting_Card_EN { get; set; }
        public string Photo_Name { get; set; }
        public Nullable<System.DateTime> Last_Update_Date { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Other_Phone_Number { get; set; }
        public string Email_Secondary { get; set; }
        public string Display_Name { get; set; }
        public Nullable<bool> PKI { get; set; }
    }
}
