//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pz_profile_his
    {
        public int UserID { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Modified { get; set; }
        public Nullable<bool> Logged { get; set; }
        public Nullable<bool> ProfileUpdated { get; set; }
        public Nullable<long> Points { get; set; }
        public string Department { get; set; }
        public string Month_His { get; set; }
    }
}
