//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pz_acclaim
    {
        public int AcclaimID { get; set; }
        public Nullable<long> ObjectTypeCode { get; set; }
        public string ObjectType { get; set; }
        public Nullable<int> ObjectID { get; set; }
        public string AcclaimType { get; set; }
        public Nullable<decimal> Score { get; set; }
        public Nullable<decimal> ScoreDisplay { get; set; }
        public Nullable<bool> Visibility { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
