//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_manager
    {
        public string CUID { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Subsidiary_Code { get; set; }
        public string Subsidiary_Label { get; set; }
        public string Manager_CUID { get; set; }
        public string Email { get; set; }
        public string Entity { get; set; }
        public string Mobile { get; set; }
        public string Phone { get; set; }
        public Nullable<bool> Is_Manager_Of_Persons { get; set; }
        public Nullable<bool> Is_Manager_Of_Internal { get; set; }
        public Nullable<bool> Is_Manager_Of_Manager { get; set; }
        public Nullable<int> Manager_Level { get; set; }
    }
}
