//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gir_purge
    {
        public long ID { get; set; }
        public string CUID { get; set; }
        public Nullable<System.DateTime> Departure_Date { get; set; }
    }
}
