//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gir_domain
    {
        public string Domain_Code { get; set; }
        public string Domain_Name { get; set; }
        public Nullable<int> Rank { get; set; }
    }
}
