//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pz_userrelation
    {
        public int RelationshipID { get; set; }
        public Nullable<int> UserID { get; set; }
        public Nullable<int> RelatedUserID { get; set; }
        public Nullable<int> RelnshipTypeID { get; set; }
        public string State { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> RetirementDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
    }
}
