//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_pz_blog
    {
        public int BlogID { get; set; }
        public string Name { get; set; }
        public string DisplayName { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreationDate { get; set; }
        public Nullable<System.DateTime> ModificationDate { get; set; }
        public Nullable<short> CMAuthentication { get; set; }
        public Nullable<sbyte> FeedEnabled { get; set; }
        public Nullable<sbyte> FeedFullContent { get; set; }
        public Nullable<int> ContainerID { get; set; }
        public Nullable<long> ContainerType { get; set; }
        public string ContainerCode { get; set; }
        public Nullable<int> Status { get; set; }
    }
}
