//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_od_location
    {
        public string Location_Code { get; set; }
        public string Country_Code { get; set; }
        public string Building_Name { get; set; }
        public string Complementary_Address { get; set; }
        public string Postal_Code { get; set; }
        public string City { get; set; }
        public string Street { get; set; }
        public Nullable<System.DateTime> Expiration_Date { get; set; }
        public Nullable<System.DateTime> Last_Update_Date { get; set; }
    }
}
