//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_gir_identity_his
    {
        public string CUID { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public Nullable<System.DateTime> Update_Date { get; set; }
        public string Description { get; set; }
        public string Domain_Code { get; set; }
        public Nullable<bool> Directory_Sync { get; set; }
        public Nullable<System.DateTime> Entry_Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> Reporting_Global { get; set; }
        public Nullable<bool> GASSI { get; set; }
        public Nullable<bool> Lock_Identity { get; set; }
        public Nullable<System.DateTime> First_Entry_Date { get; set; }
        public Nullable<bool> VIP { get; set; }
        public string Last_Name { get; set; }
        public string Subsidiary_Code { get; set; }
        public Nullable<bool> IsEnable { get; set; }
        public string Email { get; set; }
        public string Local_Id { get; set; }
        public string First_Name { get; set; }
        public string Manager_CUID { get; set; }
        public Nullable<sbyte> Title { get; set; }
        public string Category_Code { get; set; }
        public Nullable<System.DateTime> Birth_Date { get; set; }
        public Nullable<System.DateTime> Departure_Date { get; set; }
        public Nullable<System.DateTime> Last_Departure_Date { get; set; }
        public string Preferred_First_Name { get; set; }
        public string Preferred_Last_Name { get; set; }
        public string Middle_Name { get; set; }
        public string Alternate_Notification_Mail { get; set; }
        public string Partner_Code { get; set; }
        public string Sub_Employee_Type { get; set; }
        public string Prefix { get; set; }
        public string MONTH_HIS { get; set; }
    }
}
