//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GIREntities : DbContext
    {
        public GIREntities()
            : base("name=GIREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBL_Basket> TBL_Basket { get; set; }
        public virtual DbSet<TBL_BasketItem> TBL_BasketItem { get; set; }
        public virtual DbSet<TBL_BlackList> TBL_BlackList { get; set; }
        public virtual DbSet<TBL_Category> TBL_Category { get; set; }
        public virtual DbSet<TBL_Certificate> TBL_Certificate { get; set; }
        public virtual DbSet<TBL_Error> TBL_Error { get; set; }
        public virtual DbSet<TBL_ErrorAdditionalInfo> TBL_ErrorAdditionalInfo { get; set; }
        public virtual DbSet<tbl_ExportDetails> tbl_ExportDetails { get; set; }
        public virtual DbSet<tbl_FileExportConfigDetails> tbl_FileExportConfigDetails { get; set; }
        public virtual DbSet<TBL_GroupSubsidiary> TBL_GroupSubsidiary { get; set; }
        public virtual DbSet<TBL_Log> TBL_Log { get; set; }
        public virtual DbSet<TBL_MailSentInformation> TBL_MailSentInformation { get; set; }
        public virtual DbSet<TBL_News> TBL_News { get; set; }
        public virtual DbSet<TBL_Partner> TBL_Partner { get; set; }
        public virtual DbSet<TBL_Rank> TBL_Rank { get; set; }
        public virtual DbSet<TBL_Rank_GroupSubsidiary> TBL_Rank_GroupSubsidiary { get; set; }
        public virtual DbSet<TBL_Rank_Partner> TBL_Rank_Partner { get; set; }
        public virtual DbSet<TBL_RedList> TBL_RedList { get; set; }
        public virtual DbSet<TBL_User> TBL_User { get; set; }
        public virtual DbSet<TBL_WebServicesLog> TBL_WebServicesLog { get; set; }
        public virtual DbSet<TBL_Domain> TBL_Domain { get; set; }
        public virtual DbSet<TBL_Notification> TBL_Notification { get; set; }
        public virtual DbSet<TBL_NotificationDetails> TBL_NotificationDetails { get; set; }
        public virtual DbSet<TBL_OwnManagerList> TBL_OwnManagerList { get; set; }
    }
}
