//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Domain
    {
        public string VCH_DOM_Code { get; set; }
        public string VCH_DOM_ShortName { get; set; }
        public int IDE_RAN_ID { get; set; }
        public bool BOL_DOM_ReportingGlobal { get; set; }
        public bool BOL_DOM_Notif1 { get; set; }
        public bool BOL_DOM_Notif2 { get; set; }
        public bool BOL_DOM_Notif3 { get; set; }
        public bool BOL_DOM_Notif4 { get; set; }
        public bool BOL_DOM_Notif5 { get; set; }
        public bool BOL_DOM_Notif6 { get; set; }
        public bool BOL_DOM_Notif7 { get; set; }
        public string VCH_DOM_Mail { get; set; }
        public string VCH_DOM_Header { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal1 { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal2 { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal3 { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal4 { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal5 { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal6 { get; set; }
        public Nullable<bool> BOL_DOM_NotifLocal7 { get; set; }
        public Nullable<bool> SupportHomonymyRule1 { get; set; }
    }
}
