//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Certificate
    {
        public long IDE_CERT_ID { get; set; }
        public Nullable<System.DateTime> DAT_CERT_CREATIONDATE { get; set; }
        public string VCH_CERT_APPLICATION { get; set; }
        public string VCH_CERT_TITLE { get; set; }
        public string VCH_CERT_DATA { get; set; }
        public string VCH_CERT_FNAME { get; set; }
        public string VCH_CERT_LNAME { get; set; }
        public string VCH_CERT_EMAIL { get; set; }
        public string VCH_CERT_PHONE { get; set; }
        public string VCH_CERT_LASTAUTHOR { get; set; }
        public System.DateTime DAT_CERT_MODIFICATIONDATE { get; set; }
        public string VCH_CERT_LOG { get; set; }
        public string VCH_CERT_DOMAIN { get; set; }
        public bool BIT_CERT_EXTRADOMAIN { get; set; }
    }
}
