//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Partner
    {
        public string VCH_PART_Code { get; set; }
        public string VCH_PART_Label { get; set; }
        public string VCH_PART_AdminParameter { get; set; }
        public int IDE_RAN_ID { get; set; }
    
        public virtual TBL_Rank_Partner TBL_Rank_Partner { get; set; }
    }
}
