//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_ErrorAdditionalInfo
    {
        public long IDE_EAI_ID { get; set; }
        public Nullable<long> IDE_ERR_ID { get; set; }
        public string VCH_EAI_KEY { get; set; }
        public string VCH_EAI_VALUE { get; set; }
    
        public virtual TBL_Error TBL_Error { get; set; }
    }
}
