//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_RedList
    {
        public string VCH_RLL_CUID { get; set; }
        public Nullable<System.DateTime> DAT_RLL_EndDate { get; set; }
        public long IDE_RLL_ID { get; set; }
        public Nullable<bool> BIT_Deleted { get; set; }
    }
}
