//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_FileExportConfigDetails
    {
        public tbl_FileExportConfigDetails()
        {
            this.tbl_ExportDetails = new HashSet<tbl_ExportDetails>();
        }
    
        public int IDE_ID { get; set; }
        public string VCH_File_Name { get; set; }
        public string VCH_Output_File_Name { get; set; }
        public string VCH_Data_Source { get; set; }
        public string VCH_Output_File_Format { get; set; }
        public string VCH_Output_File_Encoding { get; set; }
        public string VCH_Output_File_Column_Seperator { get; set; }
        public string VCH_Export_Frequency { get; set; }
        public string VCH_Upload_Frequency { get; set; }
        public string VCH_Operation { get; set; }
        public bool BOL_Delete_Existing_File { get; set; }
        public bool BOL_Export_FileWithDate { get; set; }
        public bool BOL_Upload_FileWithDate { get; set; }
        public bool BOL_File_Compress { get; set; }
    
        public virtual ICollection<tbl_ExportDetails> tbl_ExportDetails { get; set; }
    }
}
