//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_BasketItem
    {
        public long IDE_BAI_Id { get; set; }
        public string VCH_BAI_Comment { get; set; }
        public string VCH_BAI_CuID { get; set; }
        public long NUM_BAI_IdBasket { get; set; }
        public Nullable<System.DateTime> DAT_BAI_TraitementDate { get; set; }
        public int NUM_BAI_TypeAction { get; set; }
        public int NUM_BAI_Result { get; set; }
        public string VCH_BAI_XML { get; set; }
        public string VCH_BAI_CSVRow { get; set; }
    
        public virtual TBL_Basket TBL_Basket { get; set; }
    }
}
