//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Log
    {
        public long IDE_LOG_Id { get; set; }
        public string VCH_LOG_Author { get; set; }
        public System.DateTime DAT_LOG_Date { get; set; }
        public int NUM_LOG_TypeAction { get; set; }
        public string VCH_LOG_DataModified { get; set; }
        public string VCH_LOG_Entity { get; set; }
        public string VCH_LOG_IdEntity { get; set; }
        public Nullable<int> NUM_LOG_Origin { get; set; }
    }
}
