//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Category
    {
        public long IDE_CAT_ID { get; set; }
        public string VCH_CAT_Name { get; set; }
        public string VCH_CAT_Value { get; set; }
        public string VCH_CAT_Description { get; set; }
        public string VCH_CAT_Mask { get; set; }
        public Nullable<long> NUM_CAT_ParentID { get; set; }
        public bool BIT_CAT_Obsolete { get; set; }
        public bool BIT_CAT_GASSI { get; set; }
        public bool BIT_CAT_Directory { get; set; }
        public bool BIT_CAT_ForGUI { get; set; }
        public int NUM_CAT_LifeTime { get; set; }
        public bool BIT_CAT_BirthDateMandatory { get; set; }
        public bool BIT_CAT_Replaceable { get; set; }
        public int NUM_CAT_DURATION { get; set; }
        public bool BIT_CAT_Linked { get; set; }
        public bool BIT_CAT_GroupSubsidiary { get; set; }
        public bool BIT_CAT_Partner { get; set; }
        public Nullable<bool> BIT_CAT_Prefix { get; set; }
    }
}
