//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_NotificationDetails
    {
        public string VCH_NOTIFD_DomCode { get; set; }
        public int NUM_NOTIFD_Id { get; set; }
        public string VCH_NOTIFD_MailSub { get; set; }
        public string VCH_NOTIFD_MailBody { get; set; }
    }
}
