//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_News
    {
        public long IDE_NEW_ID { get; set; }
        public string VCH_NEW_TITLE { get; set; }
        public string VCH_NEW_ABSTRACT { get; set; }
        public string VCH_NEW_CONTENT { get; set; }
        public System.DateTime DAT_NEW_BEGINDATE { get; set; }
        public System.DateTime DAT_NEW_ENDDATE { get; set; }
        public int INT_NEW_STATE { get; set; }
        public string VCH_NEW_AUTHOR { get; set; }
        public System.DateTime DAT_NEW_CREATIONDATE { get; set; }
        public string VCH_NEW_LASTAUTHOR { get; set; }
        public System.DateTime DAT_NEW_MODIFICATIONDATE { get; set; }
        public string VCH_NEW_LANG { get; set; }
    }
}
