//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_WebServicesLog
    {
        public long IDE_WSL_Id { get; set; }
        public string VCH_WSL_Cuid { get; set; }
        public System.DateTime DAT_WSL_DateCreated { get; set; }
        public string VCH_WSL_Application { get; set; }
        public string VCH_WSL_MethodName { get; set; }
        public string VCH_WSL_Xml { get; set; }
        public string VCH_WSL_Result { get; set; }
        public string VCH_WSL_Comment { get; set; }
        public System.DateTime VCH_WSL_DateModified { get; set; }
        public int NUM_WSL_ActionType { get; set; }
    }
}
