//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Error
    {
        public TBL_Error()
        {
            this.TBL_ErrorAdditionalInfo = new HashSet<TBL_ErrorAdditionalInfo>();
        }
    
        public long IDE_ERR_ID { get; set; }
        public string VCH_ERR_APPLICATION { get; set; }
        public Nullable<int> INT_ERR_CATEGORY { get; set; }
        public string VCH_ERR_TITLE { get; set; }
        public string VCH_ERR_DESCRIPTION { get; set; }
        public Nullable<System.DateTime> DAT_ERR_DATE { get; set; }
        public string VCH_ERR_USER { get; set; }
    
        public virtual ICollection<TBL_ErrorAdditionalInfo> TBL_ErrorAdditionalInfo { get; set; }
    }
}
