//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Notification
    {
        public int NUM_NOTIF_Id { get; set; }
        public string VCH_NOTIF_Type { get; set; }
        public string VCH_NOTIF_Name { get; set; }
        public string VCH_NOTIF_MailBody { get; set; }
        public string VCH_NOTIF_MailSub { get; set; }
    }
}
