//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_Basket
    {
        public TBL_Basket()
        {
            this.TBL_BasketItem = new HashSet<TBL_BasketItem>();
        }
    
        public long IDE_BAS_Id { get; set; }
        public string VCH_BAS_Author { get; set; }
        public string VCH_BAS_Applicant { get; set; }
        public System.DateTime DAT_BAS_DemandDate { get; set; }
        public Nullable<System.DateTime> DAT_BAS_EndDate { get; set; }
        public string VCH_BAS_FilePath { get; set; }
        public bool BOL_BAS_InUse { get; set; }
        public Nullable<int> NUM_BAS_NbDemand { get; set; }
        public Nullable<int> NUM_BAS_NbError { get; set; }
        public Nullable<int> NUM_BAS_NbSuccess { get; set; }
        public Nullable<int> NUM_BAS_NbToValidate { get; set; }
        public int NUM_BAS_TypeAction { get; set; }
        public Nullable<int> NUM_BAS_NbErrorInitial { get; set; }
        public Nullable<int> NUM_BAS_NbSuccessInitial { get; set; }
        public Nullable<int> NUM_BAS_NbToValidateInitial { get; set; }
    
        public virtual ICollection<TBL_BasketItem> TBL_BasketItem { get; set; }
    }
}
