//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_User
    {
        public long IDE_USR_ID { get; set; }
        public string VCH_USR_FNAME { get; set; }
        public string VCH_USR_LNAME { get; set; }
        public string VCH_USR_EMAIL { get; set; }
        public Nullable<bool> BIT_USR_ISADMIN { get; set; }
        public string VCH_USR_LANG { get; set; }
    }
}
