//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Temp
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBL_MailSentInformation
    {
        public int IDE_ID { get; set; }
        public string CH_CUID { get; set; }
        public string VCH_Email { get; set; }
        public string VCH_TypeOfMail { get; set; }
        public System.DateTime DAT_LogDateTime { get; set; }
        public int VCH_Status { get; set; }
        public string VCH_Description { get; set; }
    }
}
