//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApplication1.PeopleService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeopleService.IPeopleService")]
    public interface IPeopleService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/GetData", ReplyAction="http://tempuri.org/IPeopleService/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPeopleService/GetData", ReplyAction="http://tempuri.org/IPeopleService/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPeopleServiceChannel : ConsoleApplication1.PeopleService.IPeopleService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PeopleServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.PeopleService.IPeopleService>, ConsoleApplication1.PeopleService.IPeopleService {
        
        public PeopleServiceClient() {
        }
        
        public PeopleServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PeopleServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PeopleServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PeopleService.IAnotherInterfaceService")]
    public interface IAnotherInterfaceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnotherInterfaceService/GetEmployeeID", ReplyAction="http://tempuri.org/IAnotherInterfaceService/GetEmployeeIDResponse")]
        string GetEmployeeID(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAnotherInterfaceService/GetEmployeeID", ReplyAction="http://tempuri.org/IAnotherInterfaceService/GetEmployeeIDResponse")]
        System.Threading.Tasks.Task<string> GetEmployeeIDAsync(int id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAnotherInterfaceServiceChannel : ConsoleApplication1.PeopleService.IAnotherInterfaceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AnotherInterfaceServiceClient : System.ServiceModel.ClientBase<ConsoleApplication1.PeopleService.IAnotherInterfaceService>, ConsoleApplication1.PeopleService.IAnotherInterfaceService {
        
        public AnotherInterfaceServiceClient() {
        }
        
        public AnotherInterfaceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AnotherInterfaceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnotherInterfaceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AnotherInterfaceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetEmployeeID(int id) {
            return base.Channel.GetEmployeeID(id);
        }
        
        public System.Threading.Tasks.Task<string> GetEmployeeIDAsync(int id) {
            return base.Channel.GetEmployeeIDAsync(id);
        }
    }
}
